name:                git-sub
version:             0.1.0.0
github:              "Dansvidania/git-sub"
license:             BSD3
author:              "Danilo Amoroso"
maintainer:          "dan.j.amoroso@gmail.com"
copyright:           "2019 Danilo Amoroso"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Dansvidania/git-sub#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- text-format-simple
- text
- turtle
- optparse-applicative
- system-filepath
- bytestring

library:
  source-dirs: src

executables:
  git-sub-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - git-sub

tests:
  git-sub-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - git-sub
